
name: Apod

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout actions
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        cache: 'pip'

    - name: Download requirements
      run: pip install -r requirements.txt

    - name: Craw apod
      run: |
        python main.py

    - name: commit
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Update README.md"
        git push origin main

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}